-- MySQL Script generated by MySQL Workbench
-- sex 19 out 2018 02:18:24 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pi5_2018
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pi5_2018
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pi5_2018` DEFAULT CHARACTER SET utf8 ;
USE `pi5_2018` ;

-- -----------------------------------------------------
-- Table `pi5_2018`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`tipoUsuario` (
  `idTipoUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `descricaoTipoUsuario` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi5_2018`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `rg` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `celular` VARCHAR(20) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `observacoes` VARCHAR(200) NULL,
  `tipoUsuario_idTipoUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_tipoUsuario_idx` (`tipoUsuario_idTipoUsuario` ASC),
  CONSTRAINT `fk_usuario_tipoUsuario`
    FOREIGN KEY (`tipoUsuario_idTipoUsuario`)
    REFERENCES `pi5_2018`.`tipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi5_2018`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `dtCadastroCliente` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi5_2018`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`projeto` (
  `idProjeto` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeProjeto` VARCHAR(30) NOT NULL,
  `descricaoProjeto` VARCHAR(100) NOT NULL,
  `valorProjeto` DOUBLE NOT NULL DEFAULT '0.0',
  `duracaoProjeto` INT(10) NOT NULL,
  `dataInicioProjeto` DATE NOT NULL,
  `dataTerminoProjeto` DATE NOT NULL,
  `statusProjeto` VARCHAR(45) NOT NULL,
  `dtCadastroProjeto` TIMESTAMP NOT NULL,
  `cliente_idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`idProjeto`),
  INDEX `fk_projeto_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_projeto_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `pi5_2018`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi5_2018`.`agendaAnalista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`agendaAnalista` (
  `idAgendaAnalista` INT(11) NOT NULL AUTO_INCREMENT,
  `dataInicioDemanda` DATE NOT NULL,
  `dataTerminoDemanda` DATE NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idAgendaAnalista`),
  INDEX `fk_agendaAnalista_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_agendaAnalista_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `pi5_2018`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi5_2018`.`demanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`demanda` (
  `idDemanda` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeDemanda` VARCHAR(30) NOT NULL,
  `descricaoDemanda` VARCHAR(100) NOT NULL,
  `duracaoDemanda` INT(10) NOT NULL,
  `statusDemanda` VARCHAR(14) NOT NULL,
  `dtCadastroDemanda` TIMESTAMP NOT NULL,
  `projeto_idProjeto` INT(11) NOT NULL,
  `agendaAnalista_idAgendaAnalista` INT(11) NOT NULL,
  PRIMARY KEY (`idDemanda`),
  INDEX `fk_demanda_projeto1_idx` (`projeto_idProjeto` ASC),
  INDEX `fk_demanda_agendaAnalista1_idx` (`agendaAnalista_idAgendaAnalista` ASC),
  CONSTRAINT `fk_demanda_projeto1`
    FOREIGN KEY (`projeto_idProjeto`)
    REFERENCES `pi5_2018`.`projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_demanda_agendaAnalista1`
    FOREIGN KEY (`agendaAnalista_idAgendaAnalista`)
    REFERENCES `pi5_2018`.`agendaAnalista` (`idAgendaAnalista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi5_2018`.`recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`recurso` (
  `idRecurso` INT(11) NOT NULL AUTO_INCREMENT,
  `demanda_idDemanda` INT(11) NOT NULL,
  PRIMARY KEY (`idRecurso`),
  INDEX `fk_recurso_demanda1_idx` (`demanda_idDemanda` ASC),
  CONSTRAINT `fk_recurso_demanda1`
    FOREIGN KEY (`demanda_idDemanda`)
    REFERENCES `pi5_2018`.`demanda` (`idDemanda`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi5_2018`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`comentario` (
  `idComentario` INT(11) NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(100) NULL,
  `recurso_idRecurso` INT(11) NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_comentario_recurso1_idx` (`recurso_idRecurso` ASC),
  CONSTRAINT `fk_comentario_recurso1`
    FOREIGN KEY (`recurso_idRecurso`)
    REFERENCES `pi5_2018`.`recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi5_2018`.`anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`anexo` (
  `idAnexo` INT NOT NULL AUTO_INCREMENT,
  `anexo` VARCHAR(100) NULL,
  `recurso_idRecurso` INT(11) NOT NULL,
  PRIMARY KEY (`idAnexo`),
  INDEX `fk_anexo_recurso1_idx` (`recurso_idRecurso` ASC),
  CONSTRAINT `fk_anexo_recurso1`
    FOREIGN KEY (`recurso_idRecurso`)
    REFERENCES `pi5_2018`.`recurso` (`idRecurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pi5_2018`.`horasTrabalhadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pi5_2018`.`horasTrabalhadas` (
  `idHorasTrabalhadas` INT(11) NOT NULL AUTO_INCREMENT,
  `dataInicioHoras` TIMESTAMP NULL,
  `dataFimHoras` TIMESTAMP NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idHorasTrabalhadas`),
  INDEX `fk_horasTrabalhadas_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_horasTrabalhadas_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `pi5_2018`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Inserindo os Valores dos tipos de Usuarios no banco
INSERT INTO tipoUsuario (descricaoTipoUsuario) VALUES ('Administrador do Sistema');
INSERT INTO tipoUsuario (descricaoTipoUsuario) VALUES ('Administrador');
INSERT INTO tipoUsuario (descricaoTipoUsuario) VALUES ('Analista');

-- Inserindo o Super Usuario 
INSERT INTO usuario (nomeUsuario, cpf, rg, email, senha, telefone, celular, cargo, observacoes, tipoUsuario_idTipoUsuario) VALUES ("SuperUsuario", "null", "null", "adm@project.com.br", "abc", "null", "null", "Adm", "utilizado para cadastro de administradores" , 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- DROP SCHEMA pi5_2018;




